format_version: 10
pipelines:
  perl-Myriad:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      github:
        scm: e61157ac-2848-44a1-8587-1602b750cfc7
    stages:
    - tests:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          dzil_test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - docker run --rm -v $(pwd):/repo deriv/dzil:latest bash -c "cd /repo;
                  pwd; ./ci/dzil_test.sh"
                command: bash
                run_if: passed
          dzil_xtest:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - docker run --rm -v $(pwd):/repo deriv/dzil:latest bash -c "cd /repo;
                  pwd; ./ci/dzil_xtest.sh"
                command: bash
                run_if: passed
    - coverage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          dzil_run_cover:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - docker run --rm -v $(pwd):/repo deriv/dzil:latest bash -c "cd /repo;
                  pwd; ./ci/dzil_run_cover.sh"
                command: bash
                run_if: passed
