format_version: 10
pipelines:
  perl-Myriad:
    group: defaultGroup
    template: staged-PR
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-731d1ff:
        git: https://github.com/HarithaKotteDeriv/perl-Myriad.git
        shallow_clone: false
        auto_update: true
        branch: master
