format_version: 10
pipelines:
  2-stages:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      github:
        scm: e61157ac-2848-44a1-8587-1602b750cfc7
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - job1
                command: echo
                run_if: passed
            - exec:
                arguments:
                - '1'
                command: exit
                run_if: passed
          job2:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - job2
                command: echo
                run_if: passed
    - stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          job3:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - job3
                command: echo
                run_if: passed
