version: 2
jobs:
  build:
    docker:
      - image: regentmarkets/async-perl
        user: nobody
        auth:
          username: circle4regentmarkets
          password: $DOCKERHUB_PASSWORD
    steps:
      - add_ssh_keys:
          fingerprints:
            - "26:72:b1:08:0f:c1:3b:2b:2d:ea:61:7d:d6:11:63:fb"
      - checkout
      - run:
          name: Run test
          command: |
            prove -vmlr t/
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: perl
